Repository zeta-chain/protocol-contracts-evm, pull requests merged in 2025-07, with the labels that each got.

#538 refactor: increase payload max size for Gateway EVM
  contracts/evm/GatewayEVM.sol
  data/addresses.mainnet.json
  docs/index.md
  lib/types.ts
  pkg/erc20custody.t.sol/erc20custodytest.go
  pkg/gatewayevm.sol/gatewayevm.go
  pkg/gatewayevm.t.sol/gatewayevminboundtest.go
  pkg/gatewayevm.t.sol/gatewayevmtest.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/zetaconnectornative.t.sol/zetaconnectornativetest.go
  pkg/zetaconnectornonnative.t.sol/zetaconnectornonnativetest.go
  types/factories/GatewayEVM__factory.ts
Labels: refactor

#537 fix: use forceApprove() from SafeERC20 for all tokens approval
  contracts/evm/GatewayEVM.sol
  docs/index.md
  pkg/erc20custody.t.sol/erc20custodytest.go
  pkg/gatewayevm.sol/gatewayevm.go
  pkg/gatewayevm.t.sol/gatewayevminboundtest.go
  pkg/gatewayevm.t.sol/gatewayevmtest.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/zetaconnectornative.t.sol/zetaconnectornativetest.go
  pkg/zetaconnectornonnative.t.sol/zetaconnectornonnativetest.go
  types/factories/GatewayEVM__factory.ts
Labels: fix

#541 refactor: use native ZETA in withdraw() and withdrawAndCall()
  contracts/zevm/GatewayZEVM.sol
  contracts/zevm/interfaces/IGatewayZEVM.sol
  docs/index.md
  pkg/coreregistry.sol/coreregistry.go
  pkg/coreregistry.t.sol/coreregistrytest.go
  pkg/coreregistry.t.sol/mockgatewayzevm.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/gatewayzevm.sol/gatewayzevm.go
  pkg/gatewayzevm.t.sol/gatewayzevminboundtest.go
  pkg/gatewayzevm.t.sol/gatewayzevmoutboundtest.go
  pkg/gatewayzevmupgradetest.sol/gatewayzevmupgradetest.go
  pkg/gatewayzevmvalidations.sol/gatewayzevmvalidations.go
  pkg/igatewayzevm.sol/igatewayzevm.go
  pkg/senderzevm.sol/senderzevm.go
  pkg/systemcontract.sol/systemcontract.go
  pkg/systemcontractmock.sol/systemcontractmock.go
  pkg/testuniversalcontract.sol/testuniversalcontract.go
  pkg/zrc20.t.sol/zrc20test.go
  test/GatewayZEVM.t.sol
  test/utils/upgrades/GatewayZEVMUpgradeTest.sol
  types/GatewayZEVM.ts
  types/GatewayZEVMUpgradeTest.ts
  types/IGatewayZEVM.sol/IGatewayZEVM.ts
  types/factories/CoreRegistry__factory.ts
  types/factories/GatewayZEVMUpgradeTest__factory.ts
  types/factories/GatewayZEVMValidations__factory.ts
  types/factories/GatewayZEVM__factory.ts
  types/factories/IGatewayZEVM.sol/IGatewayZEVM__factory.ts
  types/factories/SenderZEVM__factory.ts
  types/factories/SystemContract.sol/SystemContract__factory.ts
  types/factories/SystemContractMock.sol/SystemContractMock__factory.ts
  types/factories/TestUniversalContract__factory.ts
Labels: refactor

#542 refactor: add registry setter in GatewayZEVM
  contracts/zevm/GatewayZEVM.sol
  docs/index.md
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/gatewayzevm.sol/gatewayzevm.go
  pkg/gatewayzevm.t.sol/gatewayzevminboundtest.go
  pkg/gatewayzevm.t.sol/gatewayzevmoutboundtest.go
  pkg/gatewayzevmupgradetest.sol/gatewayzevmupgradetest.go
  pkg/zrc20.t.sol/zrc20test.go
  test/GatewayZEVM.t.sol
  test/utils/upgrades/GatewayZEVMUpgradeTest.sol
  types/GatewayZEVM.ts
  types/GatewayZEVMUpgradeTest.ts
  types/factories/GatewayZEVMUpgradeTest__factory.ts
  types/factories/GatewayZEVM__factory.ts
Labels: refactor

#543 feat: implement evmProtocolChecksum script
  data/checksum/mainnet.json
  data/checksum/testnet.json
  hardhat.config.ts
  package.json
  scripts/checksum/protocolChecksum.ts
  scripts/checksum/readme.md
  yarn.lock
Labels: feat

#546 feat: add script for creating SAFE proposals
  data/checksum/mainnet.json
  data/checksum/testnet.json
  hardhat.config.ts
  package.json
  scripts/safe/create-upgrade-proposal.ts
  scripts/safe/readme.md
  yarn.lock
Labels: feat

#557 refactor: change max ZETA supply in ZetaConnectorNonNative
  contracts/evm/ZetaConnectorNonNative.sol
  data/addresses.mainnet.json
  lib/types.ts
  pkg/erc20custody.t.sol/erc20custodytest.go
  pkg/gatewayevm.t.sol/gatewayevminboundtest.go
  pkg/gatewayevm.t.sol/gatewayevmtest.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/zetaconnectornonnative.sol/zetaconnectornonnative.go
  pkg/zetaconnectornonnative.t.sol/zetaconnectornonnativetest.go
  types/factories/ZetaConnectorNonNative__factory.ts
Labels: refactor
