Repository zeta-chain/protocol-contracts-evm, pull requests merged in 2025-06, with the labels that each got.

#519 refactor: extract common validation logic into GatewayZEVMValidations library
  contracts/zevm/GatewayZEVM.sol
  contracts/zevm/interfaces/IGatewayZEVM.sol
  contracts/zevm/libraries/GatewayZEVMValidations.sol
  docs/src/SUMMARY.md
  docs/src/contracts/zevm/GatewayZEVM.sol/contract.GatewayZEVM.md
  docs/src/contracts/zevm/README.md
  docs/src/contracts/zevm/interfaces/IGatewayZEVM.sol/interface.IGatewayZEVMErrors.md
  docs/src/contracts/zevm/libraries/GatewayZEVMValidations.sol/library.GatewayZEVMValidations.md
  docs/src/contracts/zevm/libraries/README.md
  docs/src/index.md
  pkg/coreregistry.sol/coreregistry.go
  pkg/coreregistry.t.sol/coreregistrytest.go
  pkg/coreregistry.t.sol/mockgatewayzevm.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/gatewayzevm.sol/gatewayzevm.go
  pkg/gatewayzevm.t.sol/gatewayzevminboundtest.go
  pkg/gatewayzevm.t.sol/gatewayzevmoutboundtest.go
  pkg/gatewayzevmupgradetest.sol/gatewayzevmupgradetest.go
  pkg/gatewayzevmvalidations.sol/gatewayzevmvalidations.go
  pkg/igatewayzevm.sol/igatewayzevm.go
  pkg/igatewayzevm.sol/igatewayzevmerrors.go
  pkg/senderzevm.sol/senderzevm.go
  pkg/systemcontract.sol/systemcontract.go
  pkg/systemcontractmock.sol/systemcontractmock.go
  pkg/testuniversalcontract.sol/testuniversalcontract.go
  pkg/zrc20.t.sol/zrc20test.go
  test/GatewayZEVM.t.sol
  test/utils/upgrades/GatewayZEVMUpgradeTest.sol
  types/GatewayZEVM.ts
  types/GatewayZEVMValidations.ts
  types/factories/CoreRegistry__factory.ts
  types/factories/GatewayZEVMUpgradeTest__factory.ts
  types/factories/GatewayZEVMValidations__factory.ts
  types/factories/GatewayZEVM__factory.ts
  types/factories/IGatewayZEVM.sol/IGatewayZEVMErrors__factory.ts
  types/factories/IGatewayZEVM.sol/IGatewayZEVM__factory.ts
  types/factories/SenderZEVM__factory.ts
  types/factories/SystemContract.sol/SystemContract__factory.ts
  types/factories/SystemContractMock.sol/SystemContractMock__factory.ts
  types/factories/TestUniversalContract__factory.ts
  types/factories/index.ts
  types/index.ts
Labels: refactor

#532 refactor: increase payload max size to 2880 in the gateway ZEVM
  contracts/zevm/libraries/GatewayZEVMValidations.sol
  docs/book.toml
  docs/src/contracts/zevm/libraries/GatewayZEVMValidations.sol/library.GatewayZEVMValidations.md
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/gatewayzevm.sol/gatewayzevm.go
  pkg/gatewayzevm.t.sol/gatewayzevminboundtest.go
  pkg/gatewayzevm.t.sol/gatewayzevmoutboundtest.go
  pkg/gatewayzevmvalidations.sol/gatewayzevmvalidations.go
  pkg/zrc20.t.sol/zrc20test.go
  types/factories/GatewayZEVMValidations__factory.ts
  types/factories/GatewayZEVM__factory.ts
Labels: refactor

#527 feat: implement gas fee payment for ZETA withdrawals
  contracts/helpers/BaseRegistry.sol
  contracts/helpers/interfaces/IBaseRegistry.sol
  contracts/zevm/GatewayZEVM.sol
  contracts/zevm/interfaces/IGatewayZEVM.sol
  contracts/zevm/interfaces/IZRC20.sol
  contracts/zevm/interfaces/UniversalContract.sol
  data/addresses.testnet.json
  docs/index.md
  lib/types.ts
  pkg/baseregistry.sol/baseregistry.go
  pkg/coreregistry.sol/coreregistry.go
  pkg/coreregistry.t.sol/coreregistrytest.go
  pkg/coreregistry.t.sol/mockgatewayzevm.go
  pkg/gatewayevmzevm.t.sol/gatewayevmzevmtest.go
  pkg/gatewayzevm.sol/gatewayzevm.go
  pkg/gatewayzevm.t.sol/gatewayzevminboundtest.go
  pkg/gatewayzevm.t.sol/gatewayzevmoutboundtest.go
  pkg/gatewayzevmupgradetest.sol/gatewayzevmupgradetest.go
  pkg/gatewayzevmvalidations.sol/gatewayzevmvalidations.go
  pkg/ibaseregistry.sol/ibaseregistry.go
  pkg/icoreregistry.sol/icoreregistry.go
  pkg/igatewayzevm.sol/igatewayzevm.go
  pkg/igatewayzevm.sol/igatewayzevmerrors.go
  pkg/izrc20.sol/izrc20.go
  pkg/izrc20.sol/izrc20metadata.go
  pkg/registry.sol/registry.go
  pkg/registry.t.sol/mockgatewayevm.go
  pkg/registry.t.sol/registrytest.go
  pkg/senderzevm.sol/senderzevm.go
  pkg/systemcontract.sol/systemcontract.go
  pkg/systemcontractmock.sol/systemcontractmock.go
  pkg/testuniversalcontract.sol/testuniversalcontract.go
  pkg/zrc20.sol/zrc20.go
  pkg/zrc20.t.sol/zrc20test.go
  test/GatewayZEVM.t.sol
  types/BaseRegistry.ts
  types/CoreRegistry.ts
  types/GatewayZEVM.ts
  types/IBaseRegistry.sol/IBaseRegistry.ts
  types/ICoreRegistry.ts
  types/IZRC20.sol/IZRC20.ts
  types/IZRC20.sol/IZRC20Metadata.ts
  types/Registry.ts
  types/factories/BaseRegistry__factory.ts
  types/factories/CoreRegistry__factory.ts
  types/factories/GatewayZEVMUpgradeTest__factory.ts
  types/factories/GatewayZEVMValidations__factory.ts
  types/factories/GatewayZEVM__factory.ts
  types/factories/IBaseRegistry.sol/IBaseRegistry__factory.ts
  types/factories/ICoreRegistry__factory.ts
  types/factories/IGatewayZEVM.sol/IGatewayZEVMErrors__factory.ts
  types/factories/IGatewayZEVM.sol/IGatewayZEVM__factory.ts
  types/factories/IZRC20.sol/IZRC20Metadata__factory.ts
  types/factories/IZRC20.sol/IZRC20__factory.ts
  types/factories/Registry__factory.ts
  types/factories/SenderZEVM__factory.ts
  types/factories/SystemContract.sol/SystemContract__factory.ts
  types/factories/SystemContractMock.sol/SystemContractMock__factory.ts
  types/factories/TestUniversalContract__factory.ts
  types/factories/ZRC20.sol/ZRC20__factory.ts
Labels: feat

#535 chore: update TON Gateway address
  data/addresses.testnet.json
Labels: chore
